#!/bin/sh

mongodump --gzip --archive --uri=${MONGODB_URI} | s3cmd --access_key=${S3_ACCESS_KEY} --secret_key=${S3_SECRET_KEY} --host=${S3_ENDPOINT} --host-bucket="%(bucket)s.${S3_ENDPOINT}" put - ${S3_BUCKET%/}/${PREFIX}_`date +"%Y%m%d%H%M%S"`.gz
