#!/bin/sh

s3cmd --access_key=${S3_ACCESS_KEY} --secret_key=${S3_SECRET_KEY} --host=${S3_ENDPOINT} --host-bucket="%(bucket)s.${S3_ENDPOINT}" get ${S3_BUCKET%/}/$1 - | mongorestore --gzip --archive --uri=${MONGODB_URI}
